FROM maven:3.9.6-openjdk-17 AS Builder
WORKDIR ./src ./src
COPY ./pom.xml .
RUN mvn clean package


FROM openjdk:17-jdk-alpine
VOLUME /tmp
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} AttendanceService-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/AttendanceService-0.0.1-SNAPSHOT.jar"]
