version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    container_name: localhost
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  e-service:
    build: ./EmployeeService
    container_name: e-service
    environment:
      spring.datasource.url: jdbc:mysql://localhost:3306/employeedetails?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: root
      DISCOVERY_SERVICE_URL: http://eurekaserver:8761/eureka/
    restart: always
    ports:
      - "8082:8082"
    links:
      - mysqldb

  eurekaserver:
    container_name: eurekaserver
    build: ./EurekaServer
    ports:
      - "8761:8761"

  a-service:
    container_name: a-service
    build: ./AttendanceService
    environment:
      spring.datasource.url: jdbc:mysql://mysqldb:3306/employeedetails?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: root
      DISCOVERY_SERVICE_URL: http://eurekaserver:8761/eureka/
    restart: always
    ports:
      - "8083:8083"
    links:
      - mysqldb

  r-service:
    container_name: r-service
    build: ./RegistrationService
    environment:
      spring.datasource.url: jdbc:mysql://mysqldb:3306/employeedetails?createDatabaseIfNotExist=true
      spring.datasource.username: root
      spring.datasource.password: root
      DISCOVERY_SERVICE_URL: http://eurekaserver:8761/eureka/
    restart: always
    ports:
      - "8081:8081"
    links:
      - mysqldb

  gateway:
    container_name: gateway
    build: ./APIGateway
    ports:
      - "8765:8765"
    environment:
      DISCOVERY_SERVICE_URL: http://eurekaserver:8761/eureka/
    links:
      - eurekaserver
      - r-service
      - e-service
      - a-service

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: localhost
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8090:80"
